(() => {
'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
const {records,metrics,bestThresholds}=CompasModel, people=records(COMPAS_DATA);
const groups={white:people.filter(p=>p.group==='white'),black:people.filter(p=>p.group==='black')};
const labels=['점과 점수','기준선','가상 결과','실제 결과','두 오류','집단별 기준','공통 기준','토론'];
const lessons=[
 {title:'점 하나는 한 사람입니다',intro:'여기 있는 점 500개는 원본 체험의 500명 표본을 나타냅니다. 먼저 전체를 보고, 같은 사람들을 COMPAS 점수에 따라 다시 배치해 보세요.',task:'‘점수별로 정렬’을 눌러 보세요. 사람이 늘거나 줄었나요, 위치만 바뀌었나요?',figure:'500명의 기록',tag:'실제 표본 · 결과는 아직 숨김',notes:['원본 graph1과 graph2를 잇는 단계다. 격자에서는 사람 수를, 점수별 배치에서는 분포를 보여 준다.','같은 점들을 다시 배치했을 뿐 새로운 사람을 추가하지 않았다. 지금은 원을 모두 채워 표시한다. 채움은 아직 재체포 여부를 뜻하지 않는다.','COMPAS는 기록을 바탕으로 위험 점수를 매기는 도구다. 점수는 1~10의 순서 척도이며 7점을 확률 70%로 번역하지 않는다.','이 표본의 두 집단은 총 500명이다. 실제 범죄 전체, 전체 미국 인구, 전체 COMPAS 이용자를 대표하는 표본이라고 일반화하지 않는다.']},
 {title:'몇 점부터 ‘고위험’일까요?',intro:'점수만으로는 고위험과 저위험이 나뉘지 않습니다. 사람이 경계를 정해야 합니다. 여기서는 기준 점수 이상을 고위험, 그 미만을 저위험으로 분류합니다.',task:'보라색 세로선을 좌우로 끌어 보세요. 조절 막대나 방향키로도 바꿀 수 있습니다. 기준을 낮추면 어느 쪽 사람이 늘어날까요?',figure:'점수는 고정 · 분류 기준만 이동',tag:'분류 규칙 연습',notes:['원본 graph2a에 해당한다. 선은 두 점수 사이에 놓인다. 이 페이지의 ‘6점부터’는 6~10점이 고위험이라는 뜻이다.','기준을 낮추면 고위험으로 분류하는 사람이 늘고, 높이면 줄어든다. 아직 이후 기록을 보여 주지 않았으므로 맞혔는지는 판단할 수 없다.','이 체험의 고위험/저위험은 가상 분류다. 실제 법원이 점수 하나로 자동 구금하거나 석방했다는 뜻으로 설명하지 않는다.','두 극단도 확인한다. 1점부터면 전원 고위험, 11점부터면 아무도 고위험이 아니다.']},
 {title:'예측이 완벽하다면, 선 하나면 됩니다',intro:'먼저 결과를 단순하게 바꿔 놓았습니다. 1~6점은 모두 재체포되지 않고, 7~10점은 모두 재체포되는 가상 상황입니다. 빈 점과 채운 점을 선 하나로 나눌 수 있습니다.',task:'빈 점은 저위험 쪽에, 채운 점은 고위험 쪽에 모두 놓이도록 선을 옮겨 보세요. 정확도 100%를 만들 수 있나요?',figure:'가상으로 바꾼 결과 · 실제 COMPAS 성능 아님',tag:'가상 사례',notes:['원본 graph3처럼 점수 분포는 유지하고 이후 결과만 인위적으로 바꾼다. 가상이라는 점을 먼저 알린다.','빈 원은 재체포 없음, 채운 원은 재체포 있음이다. 앞으로 나오는 실제 데이터 단계에서도 같은 표시를 쓴다.','7점부터 고위험으로 정하면 500명 모두를 맞힌다. 이 성공을 COMPAS가 실제로 100% 정확하다는 증거로 쓰면 안 된다.','다음 단계에서는 점수와 사람 수를 그대로 두고 실제 기록을 펼친다. 완벽한 경계가 사라지는 이유를 점들의 섞임으로 설명한다.']},
 {title:'실제 기록에서는 점들이 섞여 있습니다',intro:'이제 실제 재체포 기록을 표시했습니다. 같은 점수 안에도 재체포된 사람과 그렇지 않은 사람이 함께 있습니다. 기준을 옮기며 가장 많이 맞히는 위치를 찾아보세요.',task:'세 곳 이상으로 선을 옮겨 정확도를 비교해 보세요. 숫자뿐 아니라 선 양쪽에 남는 빈 점과 채운 점도 보세요.',figure:'실제 기록 · 500명, 2년 안의 재체포 여부',tag:'실제 표본',notes:['원본 graph4의 중심 활동이다. 가상 단계와 달리 같은 점수 안에 빈 원과 채운 원이 섞인다.','정확도는 고위험이면서 재체포된 사람과 저위험이면서 재체포되지 않은 사람을 더해 500으로 나눈 값이다.','이 표본에서는 6점부터 고위험일 때 344명을 맞혀 정확도 68.8%가 최대다. 이 수치는 표본과 규칙에 대한 계산 결과다. 모든 COMPAS 성능으로 일반화하지 않는다.','최고 정확도를 찾은 다음, 남은 156명의 오류가 누구에게 어떤 방향으로 생겼는지 묻고 다음 단계로 넘어간다.']},
 {title:'같은 오답도, 부담은 다릅니다',intro:'고위험으로 잘못 분류하면 불필요한 제한의 근거가 될 수 있습니다. 저위험으로 잘못 분류하면 위험을 놓칠 수 있습니다. 두 오류를 따로 세어 보세요.',task:'기준을 높였다가 낮춰 보세요. 어느 오류는 줄고, 어느 오류는 늘어나나요? 각 비율 아래의 분모도 비교하세요.',figure:'빈 점을 고위험으로 / 채운 점을 저위험으로 분류하는 오류',tag:'실제 표본 · 분모 구별',notes:['원본 graph5의 두 막대를 한국어 해설과 정확한 분모로 바꾼 단계다.','위양성은 실제 양성 결과가 없는데 양성으로 판단한 경우다. 여기서는 재체포되지 않은 270명 중 고위험으로 분류된 사람이 분자다.','위음성은 실제 양성 결과가 있는데 음성으로 판단한 경우다. 여기서는 재체포된 230명 중 저위험으로 분류된 사람이 분자다.','원본의 needless jail/released 표현은 가상 처우다. 이 페이지는 실제 구금 결과인 것처럼 보이지 않게 높게/낮게 오판으로 쓴다.','오류율이 줄었다는 말만 듣지 않고 무엇을 줄였는지 되묻는다. 두 비율은 서로 다른 집단을 분모로 삼으므로 합쳐서 전체 오답률로 읽지 않는다.']},
 {title:'집단마다 기준을 바꾸면 어떨까요?',intro:'같은 500명을 원자료의 두 집단으로 나눴습니다. 같은 기준에서도 오류율은 다릅니다. 이번에는 두 선을 따로 움직이며 높게 오판하는 비율을 비슷하게 만들어 보세요.',task:'두 집단의 ‘높게 오판’ 비율을 비교하세요. 가까워졌다면, 같은 7점인 두 사람도 같은 판단을 받는지 확인하세요.',figure:'백인 198명 / 흑인 302명 · 기준선 두 개',tag:'실제 표본 · 집단별 분모',notes:['원본 graph6과 graph6a를 합친 단계다. 두 개는 같은 데이터와 계산식을 사용하며 6a에 목표 표시만 추가된다.','집단은 원자료의 Caucasian과 African-American 구분을 따른다. 집단 간 차이를 타고난 본질이나 원인으로 해석하지 않는다.','기본 6점부터에서 높게 오판하는 비율은 백인 14/129, 흑인 45/141이다. 표의 분모가 집단의 전체 인원과 다른 이유를 설명한다.','원본의 >6·>8 경계를 이 페이지에서는 7점부터·9점부터로 표기한다. 백인은 7점부터, 흑인은 9점부터로 바꾸면 높게 오판은 9.3%와 7.8%로 가까워지고, 낮게 오판은 둘 다 약 75%가 된다. 완전히 같은 비율이라고 표현하지 않는다.','같은 7점이 한 집단에는 고위험, 다른 집단에는 저위험이 된다. 특정 인종별 문턱을 현실에 도입하자는 처방이 아니라 판단 기준 간 긴장을 살피는 비교다.']},
 {title:'같은 점수에는 같은 기준을 적용한다면?',intro:'이번에는 하나의 선을 두 집단에 함께 적용합니다. 같은 점수는 같은 분류를 받습니다. 그렇다면 집단별 오류율도 비슷해질까요?',task:'공통 기준을 바꾸고 두 오류율을 비교하세요. ‘모두 저위험’ 또는 ‘모두 고위험’으로 맞추는 방법에는 어떤 문제가 있나요?',figure:'동일한 점수에는 동일한 분류 · 공통 기준선',tag:'실제 표본 · 하나의 기준',notes:['원본 graph7의 단일 기준선 비교다. 집단별 문턱 화면과 달리 한쪽만 바꾸지 못한다.','두 집단에서 같은 점수가 같은 분류를 받는 것과, 두 집단의 오류율이 같다는 것은 서로 다른 요구다.','극단을 숨기지 않는다. 전원 저위험이면 두 집단의 위양성률이 0%, 위음성률이 100%다. 전원 고위험이면 그 반대다. 숫자를 같게 만들었지만 사람을 구별하는 기능은 사라진다.','이 시뮬레이션의 특정 표본과 결정 규칙을 모든 공정성 정의가 언제나 양립 불가능하다는 일반 정리로 확대하지 않는다. 원본의 단정적 표현보다 각 선택에서 실제로 무엇을 얻고 포기했는지 보게 한다.']},
 {title:'우리의 기준을 정하고, 이유를 설명해 봅시다',intro:'지금까지 움직인 것은 사람의 점수가 아니라 분류의 기준이었습니다. 짝과 함께 하나의 기준을 고르고, 줄이고 싶은 오류와 그 대신 감수할 부담을 설명해 보세요.',task:'① 우선할 기준을 선택하고 ② 저장한 결과를 근거로 들고 ③ 다른 짝이 반대할 이유도 한 가지 적으세요.',figure:'',tag:'토론 · 근거와 부담',notes:['2~3명씩 선택한 정책을 비교한다. 숫자가 큰 쪽을 고르는 활동이나 유일한 정답을 찾는 활동으로 안내하지 않는다.','먼저 어느 오류를 줄이고 싶은지 정한다. 다음에 그 선택이 다른 오류와 같은 점수의 대우에 미치는 영향을 설명한다.','발표는 선택한 기준, 수치 근거 한 가지, 감수할 부담, 추가 확인 정보 순으로 짧게 한다. 의견이 다르면 중요하게 본 피해가 무엇인지 비교한다.','추가 확인 정보의 예: 재체포 기록을 어떻게 수집했는지, 다른 집단과 시기에도 같은 성능인지, 점수가 실제 처우에서 얼마나 중요한지, 설명·이의제기 절차가 있는지.','마무리 연결: 예측을 잘 맞히는 문제와 그 정보를 누가 어떤 목적으로 쓰는지는 구별된다. 성향 추정이 정확해도 정치적 설득에 이용하는 것까지 동의했는지는 다음 질문이다.']}
];
const defaults={step:0,sorted:false,thresholds:[6,6,6,5,6,6,6],white:6,black:6,filter:'all',saved:[],answer:'',priority:'불필요한 제한을 줄이기',tried:[],teacher:false};
let st={...defaults};try{let old=JSON.parse(localStorage.getItem('compas-classroom-v1'));if(old&&typeof old==='object')st={...st,...old};}catch{}
st.thresholds=Array.from({length:7},(_,i)=>Math.max(1,Math.min(11,Number(st.thresholds?.[i])||defaults.thresholds[i])));st.white=Math.max(1,Math.min(11,Number(st.white)||6));st.black=Math.max(1,Math.min(11,Number(st.black)||6));st.saved=Array.isArray(st.saved)?st.saved.slice(-4):[];st.tried=Array.isArray(st.tried)?st.tried:[];
let activeDrag=null,frame=null;
const pct=x=>(x*100).toFixed(1)+'%',count=x=>x.toLocaleString('ko-KR'),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem('compas-classroom-v1',JSON.stringify(st));}catch{}}
function thresholdText(k){return k===1?'모두 고위험':k===11?'모두 저위험':`${k}점부터 고위험`;}
function lowText(k){return k===1?'해당 없음':k===11?'1~10점':`1~${k-1}점`;}
function highText(k){return k===11?'해당 없음':k===1?'1~10점':`${k}~10점`;}
function current(){return st.thresholds[st.step]||6;}
function go(i){st.step=Math.max(0,Math.min(7,i));st.filter='all';location.hash=String(st.step+1);save();render();window.scrollTo({top:0,behavior:'auto'});}
$('steps').innerHTML=labels.map((s,i)=>`<a href="#${i+1}" data-step="${i}"><small>${String(i+1).padStart(2,'0')}</small>${s}</a>`).join('');
$('steps').addEventListener('click',e=>{let a=e.target.closest('a');if(a){e.preventDefault();go(+a.dataset.step);}});
function readHash(){let n=Number(location.hash.slice(1));if(Number.isInteger(n)&&n>=1&&n<=8)st.step=n-1;else st.step=Math.max(0,Math.min(7,Number(st.step)||0));}
window.addEventListener('hashchange',()=>{readHash();render();});
$('previous').onclick=()=>go(st.step-1);$('next').onclick=()=>go(st.step+1);
$('reset').onclick=()=>{st={...defaults,thresholds:[...defaults.thresholds],saved:[],tried:[]};save();go(0);};
$('teacherToggle').onclick=()=>{st.teacher=!st.teacher;save();$('teacher').hidden=!st.teacher;$('teacherToggle').setAttribute('aria-expanded',String(st.teacher));};
function render(){document.body.classList.toggle('in-lesson',st.step>0);const L=lessons[st.step];document.querySelectorAll('#steps a').forEach((a,i)=>{if(i===st.step)a.setAttribute('aria-current','step');else a.removeAttribute('aria-current');});$('eyebrow').textContent=`${String(st.step+1).padStart(2,'0')} / 08 · ${labels[st.step]}`;$('heading').textContent=L.title;$('intro').textContent=L.intro;$('taskText').textContent=L.task;$('dataTag').textContent=L.tag;$('dataTag').classList.toggle('ideal',st.step===2);$('teacherText').innerHTML='<ul>'+L.notes.map(x=>'<li>'+x+'</li>').join('')+'</ul>';$('teacher').hidden=!st.teacher;$('teacherToggle').setAttribute('aria-expanded',String(st.teacher));$('position').textContent=`${st.step+1} / 8`;$('previous').disabled=st.step===0;$('next').disabled=st.step===7;$('next').textContent=st.step===6?'토론으로':'다음 단계';$('experiment').hidden=st.step===7;$('discussion').hidden=st.step!==7;$('dotDetail').hidden=true;if(st.step===7)renderDiscussion();else{buildControls();renderExperiment();}}
function control(id,k,label){return `<div class="threshold-control"><label for="${id}"><strong>${label}</strong><span id="${id}Label">${thresholdText(k)}</span></label><input id="${id}" type="range" min="1" max="11" step="1" value="${k}" aria-valuetext="${thresholdText(k)}"><output for="${id}" id="${id}Value">${k===11?'없음':k+'점'}</output></div>`;}
function buildControls(){let html='';if(st.step===0)html=`<div class="mini-actions"><button data-action="grid" aria-pressed="${!st.sorted}">한눈에 보기</button><button data-action="sort" aria-pressed="${st.sorted}">점수별로 정렬</button></div>`;else if(st.step===5)html='<div class="group-controls">'+control('white',st.white,'백인 집단')+control('black',st.black,'흑인 집단')+'</div>';else html=control('threshold',current(),st.step===6?'두 집단의 공통 기준':'내가 정한 기준');$('controls').innerHTML=html;document.querySelectorAll('#controls input').forEach(el=>el.addEventListener('input',()=>setThreshold(el.id,+el.value)));}
function setThreshold(id,value){const k=Math.max(1,Math.min(11,Math.round(value)));if(id==='white'||id==='black')st[id]=k;else st.thresholds[st.step]=k;if(st.step===3&&!st.tried.includes(k))st.tried.push(k);save();renderExperiment();}
$('controls').addEventListener('click',e=>{const act=e.target.dataset.action;if(act==='sort'||act==='grid'){st.sorted=act==='sort';save();buildControls();renderExperiment();}});
const scoreX=s=>50+(s-.5)*90,boundaryX=k=>50+(k-1)*90;
function svgText(x,y,text,cls='',anchor='start'){return `<text x="${x}" y="${y}" class="${cls}" text-anchor="${anchor}">${escape(text)}</text>`;}
function region(k,top,bottom,id,labelsOn=true){const x=boundaryX(k);return `<rect x="${x}" y="${top}" width="${950-x}" height="${bottom-top}" fill="#f0f0f8"/>`+(labelsOn?svgText(54,top-12,'저위험으로 분류','region-label')+svgText(946,top-12,'고위험으로 분류','region-label','end'):'')+`<g class="threshold" data-drag="${id}"><rect x="${x-19}" y="${top}" width="38" height="${bottom-top}" fill="transparent"/><line x1="${x}" x2="${x}" y1="${top}" y2="${bottom}" stroke="#4f55ab" stroke-width="3"/><rect x="${x-14}" y="${(top+bottom)/2-23}" width="28" height="46" rx="10" fill="#4f55ab"/><path d="M${x-5} ${(top+bottom)/2-6}v12m10-12v12" stroke="white" stroke-width="2"/></g>`;}
function renderPlot(){let groupMode=st.step===5||st.step===6,ideal=st.step===2,hasResults=st.step>=2,hasLine=st.step>0,grid=st.step===0&&!st.sorted;const h=groupMode?530:330;let svg='<title id="plotTitle">'+escape(lessons[st.step].figure)+'</title><desc id="plotDescription">점 하나는 한 사람입니다. '+(hasResults?'빈 점은 2년 안에 재체포되지 않음, 채운 점은 재체포됨. ':'결과를 아직 표시하지 않았습니다. ')+(hasLine?'세로선은 고위험으로 분류하는 기준입니다. 조절 막대를 이용할 수도 있습니다.':'')+'</desc>';let points=[];
 if(grid){people.forEach((p,i)=>points.push({...p,x:28+(i%50)*19.2,y:53+Math.floor(i/50)*20,actual:false}));svg+=svgText(28,290,'50명씩 10줄 = 500명','group-label');}
 else{const sets=groupMode?['white','black']:['all'];sets.forEach((g,gi)=>{const rows=g==='all'?people:groups[g],base=groupMode?(gi===0?225:475):274;const top=groupMode?(gi===0?49:299):47;const k=st.step===5?st[g]:current();if(hasLine)svg+=region(k,top,base+11,st.step===5?g:'threshold');if(groupMode)svg+=svgText(50,gi===0?19:269,(g==='white'?'백인 집단 · 198명':'흑인 집단 · 302명'),'group-label');for(let score=1;score<=10;score++){const bucket=rows.filter(p=>p.score===score).sort((a,b)=>Number(b.rearrested)-Number(a.rearrested));bucket.forEach((p,j)=>points.push({...p,x:scoreX(score)-23+(j%5)*11.5,y:base-Math.floor(j/5)*11.3,actual:ideal?p.score>=7:p.rearrested,k}));svg+=svgText(scoreX(score),base+37,String(score),'score-label','middle');} });svg+=svgText(945,h-4,'COMPAS 점수','', 'end');}
 for(const p of points){const actual=p.actual,high=p.score>=(p.k||current()),type=high?(actual?'tp':'fp'):(actual?'fn':'tn');const errorVisible=hasResults&&st.step>=4;let color=groupMode?(p.group==='white'?'#4f55ab':'#128260'):'#4f55ab';let opacity=st.filter!=='all'&&type!==st.filter?.toLowerCase()?'.14':'1';if(errorVisible&&!groupMode&&st.filter!=='all'&&type===st.filter)color=type==='fp'?'#ad493b':'#356c92';svg+=`<circle class="point" data-score="${p.score}" data-group="${p.group}" data-result="${actual}" data-type="${type}" cx="${p.x}" cy="${p.y}" r="4.05" fill="${!hasResults||actual?color:'white'}" stroke="${color}" stroke-width="1.25" opacity="${opacity}"/>`;}
 // Repaint handles above the data so they remain easy to grab.
 if(hasLine){const zones=groupMode?[{g:'white',top:49,bottom:236},{g:'black',top:299,bottom:486}]:[{g:'all',top:47,bottom:285}];for(const z of zones){const k=st.step===5?st[z.g]:current(),x=boundaryX(k),id=st.step===5?z.g:'threshold';svg+=`<g class="threshold" data-drag="${id}"><rect x="${x-20}" y="${z.top}" width="40" height="${z.bottom-z.top}" fill="transparent"/><line x1="${x}" x2="${x}" y1="${z.top}" y2="${z.bottom}" stroke="#4f55ab" stroke-width="3"/><rect x="${x-14}" y="${(z.top+z.bottom)/2-23}" width="28" height="46" rx="10" fill="#4f55ab"/><path d="M${x-5} ${(z.top+z.bottom)/2-6}v12m10-12v12" stroke="white" stroke-width="2"/></g>`;}}
 if(st.step===6){const x=boundaryX(current());svg+=`<line x1="${x}" x2="${x}" y1="236" y2="299" stroke="#4f55ab" stroke-width="3" stroke-dasharray="4 4"/>`;}
 $('plot').setAttribute('viewBox',`0 0 1000 ${h}`);$('plot').innerHTML=svg;$('plot').style.maxHeight=groupMode?'530px':'';
}
function stat(label,value,detail,cls=''){return `<div class="stat ${cls}"><span class="stat-title">${label}</span><strong>${value}</strong><small>${detail}</small></div>`;}
function comparison(w,b){return `<div class="table-scroll"><table class="comparison-table"><thead><tr><th scope="col">집단</th><th scope="col">높게 오판 · 위양성률</th><th scope="col">낮게 오판 · 위음성률</th><th scope="col">전체 정확도</th></tr></thead><tbody>${[['백인',w],['흑인',b]].map(([label,m])=>`<tr><th scope="row">${label}</th><td><strong>${pct(m.fpr)}</strong><br>${m.fp} / ${m.negative}명<span class="bar"><i style="width:${m.fpr*100}%"></i></span></td><td><strong>${pct(m.fnr)}</strong><br>${m.fn} / ${m.positive}명<span class="bar"><i style="width:${m.fnr*100}%"></i></span></td><td>${pct(m.accuracy)}<br>${m.tp+m.tn} / ${m.n}명</td></tr>`).join('')}</tbody></table></div>`;}
function renderExperiment(){const i=st.step,k=current(),L=lessons[i],m=metrics(people,k,i===2);$('figureTitle').textContent=L.figure;$('legend').innerHTML=i<2?'<span><i></i>한 사람 · 결과 미표시</span>':'<span><i class="open"></i>2년 안에 재체포되지 않음</span><span><i></i>재체포됨</span>';if(i===2)$('legend').innerHTML='<span><i class="open"></i>재체포 없음으로 가정</span><span><i></i>재체포 있음으로 가정</span>';renderPlot();document.querySelectorAll('#controls input').forEach(el=>{const n=el.id==='white'||el.id==='black'?st[el.id]:k;el.value=n;el.setAttribute('aria-valuetext',thresholdText(n));$(el.id+'Label').textContent=thresholdText(n);$(el.id+'Value').textContent=n===11?'없음':n+'점';});let stats='',feedback='',extra='';
 if(i===0){stats=stat('표본의 인원','500명','같은 500명을 두 방식으로 배치합니다.')+stat('점수의 범위','1~10점','높을수록 더 높은 위험으로 평가한 점수');feedback=st.sorted?'사람 수는 그대로입니다. <b>가로 위치는 점수</b>, 각 칸의 점 개수는 그 점수를 받은 사람 수를 보여 줍니다.':'점 하나가 한 사람입니다. 이제 <b>점수별로 정렬</b>해서 어떤 점수에 사람이 많은지 살펴보세요.';}
 if(i===1){stats=stat('저위험으로 분류',count(m.low)+'명',lowText(k))+stat('고위험으로 분류',count(m.high)+'명',highText(k));feedback=`현재 <b>${thresholdText(k)}</b>입니다. 이후 재체포 기록을 아직 보지 않았으므로, 분류가 맞았는지는 알 수 없습니다.`;}
 if(i===2||i===3){stats=stat('정확도',pct(m.accuracy),`맞힌 ${m.tp+m.tn}명 ÷ 전체 500명`)+stat('맞힌 사람',count(m.tp+m.tn)+'명',`높게 분류하고 재체포됨 ${m.tp}명 + 낮게 분류하고 재체포되지 않음 ${m.tn}명`)+stat('틀린 사람',count(m.fp+m.fn)+'명',`높게 오판 ${m.fp}명 + 낮게 오판 ${m.fn}명`);if(i===2)feedback=k===7?'빈 점과 채운 점이 완전히 나뉘었습니다. <b>가상으로 만든 결과</b>이기 때문에 선 하나로 모두 맞힐 수 있습니다.':`선 오른쪽의 빈 점 ${m.fp}명, 왼쪽의 채운 점 ${m.fn}명이 남았습니다. 두 종류의 점 사이로 선을 옮겨 보세요.`;else{feedback=`실제 기록에서는 같은 점수 안에 결과가 섞입니다. 지금 기준은 <b>${m.tp+m.tn}명을 맞히지만 ${m.fp+m.fn}명을 틀립니다.</b>`;extra=`<div class="mini-actions"><button data-action="best">최고 정확도 확인</button><button data-action="save">이 기준 저장</button></div><p>지금까지 ${st.tried.length}개 기준을 비교했습니다. 정확도가 가장 높아도 어떤 오류가 남는지 다음 단계에서 확인합니다.</p>`;}}
 if(i===4){stats=stat('높게 오판 · 위양성률',pct(m.fpr),`재체포되지 않은 ${m.negative}명 중 ${m.fp}명을 고위험으로 분류`,'negative')+stat('낮게 오판 · 위음성률',pct(m.fnr),`재체포된 ${m.positive}명 중 ${m.fn}명을 저위험으로 분류`,'positive')+stat('전체 정확도',pct(m.accuracy),`맞힌 ${m.tp+m.tn}명 ÷ 전체 500명`);feedback=`높게 오판한 <b>${m.fp}명</b>과 낮게 오판한 <b>${m.fn}명</b>은 서로 다른 부담을 받습니다. 두 오류율의 분모는 각각 ${m.negative}명과 ${m.positive}명입니다.`;extra=`<div class="mini-actions"><button data-action="all" aria-pressed="${st.filter==='all'}">모든 점</button><button data-action="fp" aria-pressed="${st.filter==='fp'}">높게 오판한 점 강조</button><button data-action="fn" aria-pressed="${st.filter==='fn'}">낮게 오판한 점 강조</button><button data-action="save">이 기준 저장</button></div><p>위양성(false positive): 없던 결과를 있다고 잘못 예측. 위음성(false negative): 있던 결과를 없다고 잘못 예측.</p>`;}
 if(i===5||i===6){const wk=i===5?st.white:k,bk=i===5?st.black:k,w=metrics(groups.white,wk),b=metrics(groups.black,bk);$('stats').style.display='block';stats=comparison(w,b);const gap=Math.abs(w.fpr-b.fpr)*100;feedback=`높게 오판하는 비율의 차이는 <b>${gap.toFixed(1)}%p</b>입니다. 분모는 백인 집단의 비재체포자 ${w.negative}명, 흑인 집단의 비재체포자 ${b.negative}명입니다.`;if(i===5){const example=7;extra=`<div class="policy-example"><strong>같은 7점</strong><span>백인 집단에서는 <b>${example>=wk?'고위험':'저위험'}</b><br>흑인 집단에서는 <b>${example>=bk?'고위험':'저위험'}</b></span><span>${wk===bk?'같은 기준을 적용하고 있습니다.':'집단별 기준이 달라 같은 점수의 대우도 달라질 수 있습니다.'}</span></div><div class="mission-buttons"><button data-action="close-rates">원본의 비교 예시 보기</button><button data-action="same-six">두 기준 모두 6점으로</button><button data-action="save">이 기준 저장</button></div><p>‘원본의 비교 예시’는 백인 7점부터, 흑인 9점부터입니다. 현실에 적용하라는 권고가 아닙니다.</p>`;}else{if(k===1||k===11)feedback=`두 집단의 오류율이 같아졌습니다. 하지만 <b>${k===1?'모두를 고위험':'모두를 저위험'}으로 분류</b>해 사람을 구별하는 기능이 사라졌습니다.`;extra=`<div class="policy-example"><strong>${thresholdText(k)}</strong><span>점수가 같으면 집단과 관계없이 같은 분류를 받습니다.<br>같은 분류 기준이 같은 오류율까지 보장하는지 표를 비교하세요.</span></div><div class="mission-buttons"><button data-action="save">이 기준 저장</button><button data-action="back-groups">집단별 기준과 다시 비교</button></div>`;}}
 else $('stats').style.display='';$('stats').innerHTML=stats;$('feedback').innerHTML=feedback;$('extra').innerHTML=extra;renderTable();}
function renderTable(){const ideal=st.step===2;let head=['점수','전체','재체포 있음','재체포 없음'];let rows=[];for(let score=1;score<=10;score++){const r=people.filter(p=>p.score===score),yes=r.filter(p=>ideal?p.score>=7:p.rearrested).length;rows.push([score,r.length,yes,r.length-yes]);}$('tableDetails').hidden=st.step<2;$('dataTable').innerHTML='<table class="count-table"><caption>'+ (ideal?'가상으로 바꾼 결과의 인원':'실제 표본의 점수별 인원')+'</caption><thead><tr>'+head.map(h=>'<th scope="col">'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map((x,i)=>i===0?'<th scope="row">'+x+'</th>':'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table><p>정확도 = (높게 분류하고 재체포됨 + 낮게 분류하고 재체포되지 않음) ÷ 전체 인원</p>';}
$('extra').addEventListener('click',e=>{const a=e.target.closest('button')?.dataset.action;if(!a)return;if(['all','fp','fn'].includes(a)){st.filter=a;renderExperiment();}if(a==='best'){const best=bestThresholds(people);setThreshold('threshold',best[0].k);$('feedback').innerHTML=`이 표본에서는 <b>${thresholdText(best[0].k)}일 때 정확도 ${pct(best[0].accuracy)}</b>가 가장 높습니다. 그래도 ${best[0].fp+best[0].fn}명의 오류가 남습니다.`;}if(a==='close-rates'){st.white=7;st.black=9;save();renderExperiment();}if(a==='same-six'){st.white=6;st.black=6;save();renderExperiment();}if(a==='back-groups')go(5);if(a==='save')saveChoice();});
function saveChoice(){let c=st.step===5?{type:'separate',white:st.white,black:st.black}:{type:'common',k:current()};if(!st.saved.some(x=>JSON.stringify(x)===JSON.stringify(c)))st.saved.push(c);st.saved=st.saved.slice(-4);save();$('feedback').innerHTML=`이 기준을 저장했습니다. <b>8단계 토론</b>에서 다른 선택과 비교할 수 있습니다. (${st.saved.length}개 저장)`;}
$('plot').addEventListener('pointerdown',e=>{const g=e.target.closest('[data-drag]');if(g){e.preventDefault();activeDrag=g.dataset.drag;$('plot').setPointerCapture(e.pointerId);}});
$('plot').addEventListener('pointermove',e=>{if(!activeDrag)return;e.preventDefault();const pt=$('plot').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const local=pt.matrixTransform($('plot').getScreenCTM().inverse());const k=Math.max(1,Math.min(11,Math.round((local.x-50)/90)+1));const id=activeDrag,old=id==='white'||id==='black'?st[id]:current();if(k!==old)setThreshold(id,k);});
function endDrag(e){if(activeDrag){activeDrag=null;if($('plot').hasPointerCapture(e.pointerId))$('plot').releasePointerCapture(e.pointerId);}}
$('plot').addEventListener('pointerup',endDrag);$('plot').addEventListener('pointercancel',endDrag);$('plot').addEventListener('click',e=>{const d=e.target.closest('.point')?.dataset;if(!d||st.step<2)return;const k=st.step===5?st[d.group]:current(),actual=d.result==='true',high=+d.score>=k;$('dotDetail').hidden=false;$('dotDetail').innerHTML=`<b>${d.score}점</b> · ${st.step===2?'가상 결과: ':''}${actual?'재체포됨':'재체포되지 않음'} · 현재 기준에서는 <b>${high?'고위험':'저위험'}</b> → ${high===actual?'맞힌 경우':high?'높게 오판(위양성)':'낮게 오판(위음성)'}.<br>집계값을 점으로 펼친 예시이며 특정 개인을 식별하는 기록은 아닙니다.`;});
function choiceText(c){return c.type==='separate'?`백인 ${thresholdText(c.white)} / 흑인 ${thresholdText(c.black)}`:`공통 기준: ${thresholdText(c.k)}`;}
function renderDiscussion(){const saved=st.saved.map((c,i)=>{let w=metrics(groups.white,c.type==='separate'?c.white:c.k),b=metrics(groups.black,c.type==='separate'?c.black:c.k);return `<div class="saved-choice"><b>선택 ${i+1} · ${choiceText(c)}</b><br>높게 오판: 백인 ${pct(w.fpr)}, 흑인 ${pct(b.fpr)}<br>낮게 오판: 백인 ${pct(w.fnr)}, 흑인 ${pct(b.fnr)}</div>`;}).join('');$('discussion').innerHTML=`<div class="discussion-grid"><section><h3>1. 무엇을 먼저 지킬까요?</h3><label for="priority">짝과 합의한 우선 기준</label><select id="priority">${['불필요한 제한을 줄이기','위험을 놓치는 오류를 줄이기','같은 점수에 같은 기준 적용하기','집단 간 오류율 차이를 줄이기'].map(s=>`<option${s===st.priority?' selected':''}>${s}</option>`).join('')}</select><h3 style="margin-top:25px">2. 선택한 수치를 근거로 들기</h3>${saved||'<p>아직 저장한 기준이 없습니다. 4~7단계에서 기준을 움직인 뒤 ‘이 기준 저장’을 눌러 보세요.</p><button data-discuss="explore">기준 비교하러 가기</button>'}<p>여러 선택이 있다면 어느 쪽을 택할지, 다른 선택에서는 무엇을 포기했는지 비교하세요.</p></section><section><h3>3. 우리의 선택 설명하기</h3><ol><li>어떤 기준을 골랐고, 어떤 오류를 먼저 줄였나요?</li><li>대신 늘어날 수 있는 오류는 무엇이며, 누가 부담을 지나요?</li><li>실제 결정에 쓰기 전에 무엇을 더 확인해야 하나요?</li></ol><label for="answer">짝과 정리한 답</label><textarea id="answer" placeholder="우리는 ___를 먼저 지키기 위해 ___ 기준을 골랐다.\n수치로 보면 ___.\n대신 ___의 부담이 커질 수 있다.\n실제 사용 전에는 ___도 확인해야 한다.">${escape(st.answer)}</textarea><div class="answer-actions"><button data-discuss="copy">답 복사</button><small id="copyStatus">답은 이 기기에만 남습니다.</small></div><p style="margin-top:20px"><b>다른 짝에게 물어볼 질문</b><br>“우리가 줄이려는 피해보다, 당신들이 줄이려는 피해가 더 중요하다고 생각한 이유는 무엇인가요?”</p></section></div>`;$('priority').onchange=e=>{st.priority=e.target.value;save();};$('answer').oninput=e=>{st.answer=e.target.value;save();};}
$('discussion').addEventListener('click',async e=>{let a=e.target.dataset.discuss;if(a==='explore')go(4);if(a==='copy'){const txt=`우선 기준: ${st.priority}\n${st.saved.map(choiceText).join('\n')}\n\n${st.answer}`;try{await navigator.clipboard.writeText(txt);$('copyStatus').textContent='답을 복사했습니다.';}catch{$('answer').focus();$('answer').select();$('copyStatus').textContent='선택된 답을 직접 복사해 주세요.';}}});
readHash();render();
})();
